### ISSUE TITLE
Migration does not generate unique index

### ISSUE THREAD

**Issue by evan-mark4s** [phalcon/phalcon-devtools#518]
I know this issue has been added before but that one is closed without resolved.

So this is my Mysql table definition
```sql
CREATE TABLE `tokens` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `token` varchar(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `token_UNIQUE` (`token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
And the migration generator did not generate the unique index.
```php
new Index('token_UNIQUE', array('token')),
```
I think it should be like this
```php
new Index('token_UNIQUE', array('token'), 'UNIQUE'),
```
I checked function `getIndexDefinition` on `\Phalcon\Generator\Snippet.php` and it doesn't have placeholder for the `'UNIQUE'` type.
Hope this can be fixed. For now I have to add the `'UNIQUE'` type manually for each table, which is error prone.

**Comment by sergeyklay** [comment]
@evan-mark4s Good catch. Will be fixed soon

**Comment by sergeyklay** [comment]
@evan-mark4s 
I started working on this issue. Unfortunately the problem is complex. Now [I've fixed](https://github.com/phalcon/cphalcon/pull/10998) this bug on SQLite. The next step is MySQL.

**Comment by sergeyklay** [comment]
@evan-mark4s
Now [I've fixed](https://github.com/phalcon/cphalcon/pull/11039) this bug on MySQL. The next step is PostgreSQL.

Can you please try to test Phalcon `2.0.x` and Devtools `2.0.x`?

**Comment by alexxk82** [comment]
Sorry, but it's still not working in Phalcon 2.0.5! :(

**Comment by rianorie** [comment]
Of course not.. First it won't be in 2.0.5 but whichever next release is
coming. Secondly, the pull request got denied because I wasn't thinking
straight and made my changes in the wrong branch. It'll be forthcoming soon
though!

**Comment by sergeyklay** [comment]
It will never work on Phalcon 2.0.5

**Comment by sergeyklay** [comment]
Phalcon 2.0.5 **released** before these changes

**Comment by alexxk82** [comment]
Ok, thanks!

**Comment by alexxk82** [comment]
Ok, i updated to 2.0.8.. when i create a new migration, my migration-file looks fine.

```
new Index('users_id_fk_app_id_fk', array('users_id_fk', 'app_id_fk'), 'UNIQUE'),
```

But a migration --action=run will only create a normal INDEX on this columns, no UNIQUE INDEX

```
Phalcon DevTools (2.0.8)
.....
1448632660.9336: ALTER TABLE `users_uid` ADD INDEX `users_id_fk_app_id_fk` (`users_id_fk`, `app_id_fk`)  => 1448632660.9506 (0.017000913619995)
```

**Comment by sergeyklay** [comment]
I've fixed this in [2.0.9](https://github.com/phalcon/cphalcon/releases/tag/phalcon-v2.0.9) (current stable version). See [CHANGELOG.md](https://github.com/phalcon/cphalcon/blob/2.0.x/CHANGELOG.md)

**Comment by alexxk82** [comment]
Sorry, but i think in 2.0.9 its still not working correctly. I have a database with a UNIQUE-index over 2 columns of a table. Then i use phalcon devtools to do a migration-generate for this table..

```phalcon migration --action=generate --migrations=migration --config=config/config_local.php --table=[table_name]```

It will create a migration-file where this UNIQUE-index is only defined as normal index.. there are no informations collected in this migration-file, if its a unique key, a primary key or something else...

When i run my migration on my staging-server, i do it by this command...
```phalcon migration --action=run --migrations=migration --config=config/config_local.php```

In my dev-environment, it was a UNIQUE-key and on my staging-environment the migration only creates a normal index on my database, no UNIQUE-index. 

I also tested the new beta version 2.1.0... there is alway the same error. The phalcon-devtools currently can't work with index-types when creating a new migration-version.

**Comment by sergeyklay** [comment]
Phalcon is built under [Travis CI](https://travis-ci.org/) service.
Every commit pushed to this repository will queue a build into the continuous integration service and will run all tests to ensure that everything is going well and the project is stable.

Current tests in master: https://github.com/phalcon/cphalcon/blob/master/unit-tests/DbDescribeTest.php#L818-L833

Current build status: [![Build Status](https://img.shields.io/travis/phalcon/cphalcon/master.svg?style=flat-square)](https://travis-ci.org/phalcon/cphalcon)

**Comment by sergeyklay** [comment]
```sql
CREATE TABLE `slug` (
  `id` smallint(6) unsigned NOT NULL AUTO_INCREMENT,
  `language` varchar(2) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'bb',
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `slug` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `brand` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `sort` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `language2` varchar(2) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'bb',
  PRIMARY KEY (`id`,`language`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

```php
<?php

use Phalcon\Db\Adapter\Pdo\Mysql;

$connection = new Mysql(
    [
        'host'        => 'localhost',
        'username'    => 'root',
        'password'    => '',
        'dbname'      => 'phalcon_test',
        'charset'     => 'utf8',
    ]
);

$indexes = $connection->describeIndexes('slug');

foreach ($indexes as $index) {
    var_dump($index->getType());
}
````

```sh
$ php ~/tmp/index_mysql.php 
string(7) "PRIMARY"
string(6) "UNIQUE"
```

```sh
$ php --ri phalcon

phalcon


Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 2.0.9
Build Date => Nov 25 2015 21:23:38
Powered by Zephir => Version 0.9.1a-dev

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
```

**Comment by alexxk82** [comment]
Ok, your testscript gives me two empty strings.

```
string(0) "" string(0) ""
```

This is my phalcon output of your command above.
```
Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 2.0.9
Build Date => Nov 26 2015 08:06:43
Powered by Zephir => Version 0.8.0a

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
```

**Comment by sergeyklay** [comment]
Can you please provide database schema?

**Comment by alexxk82** [comment]
I created this test on a new test-database (InnoDB) and executed your query from above.

I did this test on a Virtual Box with Ubuntu (PHP 5.5.9, Phalcon 2.0.9) and on my Windows 7 with phalcon 2.1.0  (PHP 5.4.22, Phalcon 2.1.0 BETA 2)

The phalcon devtools executes 4 queries to build a new migration file.. the output on your test-table is this...

```DESCRIBE slug;```
![describe query](https://picload.org/image/piwllwr/describe_slug.png)

```SHOW INDEXES FROM slug;```
![show indexes](https://picload.org/image/piwllpw/show_indexes.png)

```SELECT TABLES.TABLE_TYPE AS table_type,TABLES.AUTO_INCREMENT AS auto_increment,TABLES.ENGINE AS engine,TABLES.TABLE_COLLATION AS table_collation FROM INFORMATION_SCHEMA.TABLES WHERE TABLES.TABLE_NAME = 'slug'```
![table_type](https://picload.org/image/piwllpi/table_type.png)

**Comment by alexxk82** [comment]
Now i created a new migration of your table.

```
root@vbox:/var/www/phalcon_test$ phalcon migration --action=generate --migrations=migration --config=config/config.php --table=slug

Phalcon DevTools (2.0.9)

1448952520.8472: DESCRIBE `phalcon_test`.`slug`  => 1448952520.8483 (0.0011730194091797)
1448952520.8555: SHOW INDEXES FROM `phalcon_test`.`slug`  => 1448952520.8563 (0.00083613395690918)
1448952520.8576: SELECT TABLE_NAME,COLUMN_NAME,CONSTRAINT_NAME,REFERENCED_TABLE_SCHEMA,REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE REFERENCED_TABLE_NAME IS NOT NULL AND CONSTRAINT_SCHEMA = 'phalcon_test' AND TABLE_NAME = 'slug'  => 1448952520.8586 (0.0010859966278076)
1448952520.8589: SELECT TABLES.TABLE_TYPE AS table_type,TABLES.AUTO_INCREMENT AS auto_increment,TABLES.ENGINE AS engine,TABLES.TABLE_COLLATION AS table_collation FROM INFORMATION_SCHEMA.TABLES WHERE TABLES.TABLE_SCHEMA = 'phalcon_test' AND TABLES.TABLE_NAME = 'slug'  => 1448952520.86 (0.0010428428649902)
                                                      
Success: Version 1.0.0 was successfully generated  

```

This is the generated migration-file ;)
``` 
<?php 

use Phalcon\Db\Column;
use Phalcon\Db\Index;
use Phalcon\Db\Reference;
use Phalcon\Mvc\Model\Migration;

class SlugMigration_100 extends Migration
{

    public function up()
    {
        $this->morphTable(
            'slug',
            array(
            'columns' => array(
                new Column(
                    'id',
                    array(
                        'type' => Column::TYPE_INTEGER,
                        'unsigned' => true,
                        'notNull' => true,
                        'autoIncrement' => true,
                        'size' => 6,
                        'first' => true
                    )
                ),
                new Column(
                    'language',
                    array(
                        'type' => Column::TYPE_VARCHAR,
                        'notNull' => true,
                        'size' => 2,
                        'after' => 'id'
                    )
                ),
                new Column(
                    'name',
                    array(
                        'type' => Column::TYPE_VARCHAR,
                        'notNull' => true,
                        'size' => 255,
                        'after' => 'language'
                    )
                ),
                new Column(
                    'slug',
                    array(
                        'type' => Column::TYPE_VARCHAR,
                        'notNull' => true,
                        'size' => 20,
                        'after' => 'name'
                    )
                ),
                new Column(
                    'brand',
                    array(
                        'type' => Column::TYPE_VARCHAR,
                        'size' => 100,
                        'after' => 'slug'
                    )
                ),
                new Column(
                    'sort',
                    array(
                        'type' => Column::TYPE_INTEGER,
                        'unsigned' => true,
                        'notNull' => true,
                        'size' => 3,
                        'after' => 'brand'
                    )
                ),
                new Column(
                    'language2',
                    array(
                        'type' => Column::TYPE_VARCHAR,
                        'notNull' => true,
                        'size' => 2,
                        'after' => 'sort'
                    )
                )
            ),
            'indexes' => array(
                new Index('PRIMARY', array('id', 'language')),
                new Index('slug', array('slug'))
            ),
            'options' => array(
                'TABLE_TYPE' => 'BASE TABLE',
                'AUTO_INCREMENT' => '1',
                'ENGINE' => 'InnoDB',
                'TABLE_COLLATION' => 'utf8_unicode_ci'
            )
        )
        );
    }
}

```

**Comment by sergeyklay** [comment]
```sh
$ mkdir /tmp
$ phalcon project store simple
$ cd store
$ sed -i "s/\('dbname'\s\+ => \)'test',/\1'phalcon_test',/g" app/config/config.php
```

```sql
CREATE TABLE `slug` (
  `id` smallint(6) unsigned NOT NULL AUTO_INCREMENT,
  `language` varchar(2) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'bb',
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `slug` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `brand` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `sort` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `language2` varchar(2) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'bb',
  PRIMARY KEY (`id`,`language`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

```sh
$ phalcon migration --action=generate --table=slug

Phalcon DevTools (2.0.9)

1448996409.59: DESCRIBE `phalcon_test`.`slug`  => 1448996409.5906 (0.00060701370239258)
1448996409.5909: SHOW INDEXES FROM `phalcon_test`.`slug`  => 1448996409.5911 (0.00019693374633789)
1448996409.5913: SELECT TABLE_NAME,COLUMN_NAME,CONSTRAINT_NAME,REFERENCED_TABLE_SCHEMA,REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE REFERENCED_TABLE_NAME IS NOT NULL AND CONSTRAINT_SCHEMA = 'phalcon_test' AND TABLE_NAME = 'slug'  => 1448996409.592 (0.00070881843566895)
1448996409.5921: SELECT TABLES.TABLE_TYPE AS table_type,TABLES.AUTO_INCREMENT AS auto_increment,TABLES.ENGINE AS engine,TABLES.TABLE_COLLATION AS table_collation FROM INFORMATION_SCHEMA.TABLES WHERE TABLES.TABLE_SCHEMA = 'phalcon_test' AND TABLES.TABLE_NAME = 'slug'  => 1448996409.5923 (0.00019001960754395)
```

```sh
$ cat app/migrations/1.0.0/slug.php
```

```php
<?php 

use Phalcon\Db\Column;
use Phalcon\Db\Index;
use Phalcon\Db\Reference;
use Phalcon\Mvc\Model\Migration;

/**
 * Class SlugMigration_100
 */
class SlugMigration_100 extends Migration
{
    /**
     * Define the table structure
     *
     * @return void
     */
    public function morph()
    {
        $this->morphTable('slug', array(
                'columns' => array(
                    new Column(
                        'id',
                        array(
                            'type' => Column::TYPE_INTEGER,
                            'unsigned' => true,
                            'notNull' => true,
                            'autoIncrement' => true,
                            'size' => 6,
                            'first' => true
                        )
                    ),
                    new Column(
                        'language',
                        array(
                            'type' => Column::TYPE_VARCHAR,
                            'default' => "bb",
                            'notNull' => true,
                            'size' => 2,
                            'after' => 'id'
                        )
                    ),
                    new Column(
                        'name',
                        array(
                            'type' => Column::TYPE_VARCHAR,
                            'notNull' => true,
                            'size' => 255,
                            'after' => 'language'
                        )
                    ),
                    new Column(
                        'slug',
                        array(
                            'type' => Column::TYPE_VARCHAR,
                            'notNull' => true,
                            'size' => 20,
                            'after' => 'name'
                        )
                    ),
                    new Column(
                        'brand',
                        array(
                            'type' => Column::TYPE_VARCHAR,
                            'size' => 100,
                            'after' => 'slug'
                        )
                    ),
                    new Column(
                        'sort',
                        array(
                            'type' => Column::TYPE_INTEGER,
                            'default' => "0",
                            'unsigned' => true,
                            'notNull' => true,
                            'size' => 3,
                            'after' => 'brand'
                        )
                    ),
                    new Column(
                        'language2',
                        array(
                            'type' => Column::TYPE_VARCHAR,
                            'default' => "bb",
                            'notNull' => true,
                            'size' => 2,
                            'after' => 'sort'
                        )
                    )
                ),
                'indexes' => array(
                    new Index('PRIMARY', array('id', 'language'), 'PRIMARY'),
                    new Index('slug', array('slug'), 'UNIQUE')
                ),
                'options' => array(
                    'TABLE_TYPE' => 'BASE TABLE',
                    'AUTO_INCREMENT' => '1',
                    'ENGINE' => 'InnoDB',
                    'TABLE_COLLATION' => 'utf8_unicode_ci'
                ),
            )
        );
    }

    /**
     * Run the migrations
     *
     * @return void
     */
    public function up()
    {

    }

    /**
     * Reverse the migrations
     *
     * @return void
     */
    public function down()
    {

    }

}

```

```sh
$ mysql --version
mysql  Ver 14.14 Distrib 5.6.27, for debian-linux-gnu (x86_64) using  EditLine wrapper
```

```sh
$ php -r 'echo Phalcon\Version::get(), PHP_EOL;'
2.0.9
```

```sh
klay@cerberus:~/projects/php/phalcon/devtools$ git log --name-status HEAD^..HEAD
commit 6cac84880afd74ac102de6f323b3148c66b1ea03
Merge: e435375 302278e
Author: Serghei Iakovlev <sergeyklay@users.noreply.github.com>
Date:   Fri Nov 27 20:44:48 2015 +0200

    Merge pull request #567 from rianorie/migration-generate-onupdate-ondelete-constraint
    
    Added ondelete and onupdate to the generated reference arrays

commit 302278e44929774ec50ce1ad72a56113ef54bafd
Author: Rian Orie <rian.orie@gmail.com>
Date:   Fri Nov 27 19:21:26 2015 +0100

    Added ondelete and onupdate to the generated reference arrays

M       scripts/Phalcon/Mvc/Model/Migration.php
```

**Comment by alexxk82** [comment]
Ok, thats the problem... i can't see your commit from above. Its another server with ubuntu where i installed phalcon today.

```
root@h254232:/var/www/phalcon_app/phalcon-devtools# git log --name-status HEAD^..HEAD
commit 20f978d4098f3db766888ce7d015f85a5d7436ee
Merge: c2e5aff e435375
Author: Serghei Iakovlev <sergeyklay@users.noreply.github.com>
Date:   Wed Nov 25 23:36:49 2015 +0200

    Merge pull request #564 from phalcon/2.0.x

    2.0.9

commit e43537549be54377ffb0b19b7178ad8f2c207ee3
Author: Serghei Iakovlev <sadhooklay@gmail.com>
Date:   Wed Nov 25 23:34:19 2015 +0200

    Added 2.0.9 stubs

A       ide/2.0.9/Phalcon/Acl.php
A       ide/2.0.9/Phalcon/Config.php
A       ide/2.0.9/Phalcon/Crypt.php
A       ide/2.0.9/Phalcon/CryptInterface.php
A       ide/2.0.9/Phalcon/Db.php
A       ide/2.0.9/Phalcon/Debug.php
A       ide/2.0.9/Phalcon/Di.php
A       ide/2.0.9/Phalcon/DiInterface.php
A       ide/2.0.9/Phalcon/Dispatcher.php
A       ide/2.0.9/Phalcon/DispatcherInterface.php

```

**Comment by vinaysikarwar** [comment]
I used like this for unique column and worked fine for me in version 2.
// Define new unique index
$index_unique = new \Phalcon\Db\Index(
    'column_UNIQUE',
    [
        'column',
        'column'
    ],
    'UNIQUE'
);
